### ISSUE TITLE
multiple cameras, multiple views

### ISSUE THREAD

**Issue by qaisjp** [BlackBulletIV/ammo#15]
instead of worlds being assigned a camera, cameras should be assigned a world.
Camera's are assigned to a View (a new class).
Views are assigned a world. One world per view, multiple views per world.
View:draw() has to be called in order to draw the world.

This allows split-screen games.
For example:

```
local world = World:new()
local half_width, height = love.graphics.width/2, love.graphics.height

local left = View:new(0, 0, half_width, height) -- draws to left side
local leftCamera = Camera:new() -- create a camera, that handles positioning
left.world = world -- tells what the view should manage positioning
left.camera = leftCamera -- tells the view to use that camera..
leftCamera:setPosition(0,0) -- sets the camera position

local right = View:new(half_width, 0, half_width, height) -- draws to right side
local rightCamera = Camera:new()
right.world = world
right.camera = rightCamera
rightCamera:setPosition(500, 50)
```

**Comment by qaisjp** [comment]
Closing since this is almost half a decade old. Time flies!

**Comment by BlackBulletIV** [comment]
Damn, it sure does. Still may implement this feature at some stage, the camera system as a whole kinda needs looking at, just not very game dev oriented these days.
